site_name: Python Liquid2
site_description: Liquid templates for Python.
site_url: https://jg-rp.github.io/python-liquid2/

theme:
  name: material
  palette:
    primary: white
  features:
    - content.code.copy
    - navigation.top
    - navigation.sections
    - navigation.tabs
    - navigation.prune

repo_name: jg-rp/python-liquid2
repo_url: https://github.com/jg-rp/python-liquid2
edit_uri: ""

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_signature_annotations: true
            show_root_heading: true
            separate_signature: true
            docstring_section_style: "spacy"

nav:
  - Home:
      - Introduction: "index.md"
      - Quick start: "quick_start.md"
      - Liquid Syntax: "syntax.md"
      - Conventions: "conventions.md"
      - Migration guide: "migration.md"
  - User guide:
      - Rendering templates: "rendering_templates.md"
      - Liquid environments: "environment.md"
      - Loading templates: "loading_templates.md"
      - Render context data: "render_context.md"
      - Variables, types and drops: "variables_and_drops.md"
      - Whitespace control: "whitespace_control.md"
      - Internationalization and localization: "babel.md"
      - Static template analysis: "static_analysis.md"
      - Custom filters: "custom_filters.md"
      - Custom tags: "custom_tags.md"
      - Custom template loaders: "custom_loaders.md"
  - Tag reference:
      - Default tags: "tag_reference.md"
      - Optional tags: "optional_tags.md"
  - Filter reference:
      - Default filters: "filter_reference.md"
      - Optional filters: "optional_filters.md"
  - API reference:
      - Convenience functions: "api/convenience.md"
      - Environment: "api/environment.md"
      - Template: "api/template.md"
      - Loaders: "api/loaders.md"
      - Exceptions: "api/exceptions.md"
      - Builtin: "api/builtin.md"
      - AST: "api/ast.md"
      - Render context: "api/render_context.md"
      - Filter helpers: "api/filter.md"
      - Tag: "api/tag.md"
      - Undefined: "api/undefined.md"
      - Babel: "api/babel.md"
      - Messages: "api/messages.md"
      - Tokens: "api/tokens.md"
      - WhitespaceControl: "api/whitespace_control.md"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables

watch:
  - liquid2

hooks:
  - docs/.overrides/hooks/shortcodes.py

extra_css:
  - stylesheets/extra.css
